### ISSUE TITLE
Problem Creating Remote New Folders 

### ISSUE THREAD

**Issue by toonbon** [morassman/atom-commander#37]
There seems to be a problem creating new folders on a remote server.  In the image below, after navigating to the **wp-content\plugins** folder  I tried to add the folder **Ultimate_VC_dummy** using the F7 key, but the folder didn't appear in wp-content\plugins, even after refreshing.  Then after going back to the root I see that it was actually put at \wp-content\plugins\.  The same thing happened with the folders dumbfolder, typedumb, and typesfordummies.

![ac1](https://cloud.githubusercontent.com/assets/4875886/18092988/3f5bcaca-6e83-11e6-97d0-356d308c218b.jpg)

**Comment by morassman** [comment]
I am not able to reproduce this behaviour with my server. Creating folders works fine. It may be an issue with the server you are accessing or the SFTP library Atom Commander uses (or a combination thereof).

It won't be easy for me to debug this without being able to reproduce it, but I'll see what I can do.  It may help if you can tell me more about the server you are accessing.

1.) Are you hosting this server locally?
2.) If not, where is it hosted.
3.) Would I be able to create a (free) account to test with?

**Comment by morassman** [comment]
From one of the other issues you logged it sound like you are using WP Engine? Unfortunately they don't have a free option :(

**Comment by toonbon** [comment]
I have a sandbox install - steve2 -  you can use.  I've temporarily changed the SFTP password for you to Atomcommander1:

![ac2](https://cloud.githubusercontent.com/assets/4875886/18100500/1acc24da-6ea0-11e6-8e1e-dabf4dff7635.jpg)

The WordPress account for the install is at http://steve2.wpengine.com/, if you care. 

WP Engine tech support is 24/7 at 1-877-973-6446 and they've always been very helpful.  Just tell them you have an install at steve2.

Hope that helps.

Steve

**Comment by toonbon** [comment]
I notice also that deleting from inside a remote folder doesn't work either so I wonder if it too is accessing the root.

Steve

**Comment by morassman** [comment]
Thanks! That's very kind of you!

I logged on and created a folder called AC_Test in the root. I was able to create a sub folder in it and then another sub folder in that one. I was also able to create two files in the deepest folder and was able to rename and then delete one of the files.

I think, though, that I know what the problem is. The folders you created have `\` in them, which is what is used on Windows as a path separator. It's suppose to be `/` when working with FTP. I think the platform's file separator is being used, which will explain why it's working for me (I use OSX, which uses `/`)

I'm pretty sure this is the issue, but I'm not sure where the incorrect separator crept in. With the latest version of Atom Commander the latest version of the SFTP library is also being used. AFAIK this used to work on Windows, so it may be a bug in the library.

I have access to a Windows PC at work, so I'll be able to narrow it down there. Thank you for the login details. If you don't mind I'd like to use it a bit more for testing. I'm sure with it I'll be able to find the issue and I'll let you know when I do.

**Comment by toonbon** [comment]
Ok.  No problem.  Use it as long as you like.

**Comment by morassman** [comment]
It was as I suspected. The local file system's path separator was being used. This is fixed in v0.7.2

**Comment by toonbon** [comment]
I upgraded to 0.7.2 but I'm still unable to create new folders where I want them.  If I open the wp-content folder and then do an F7 and enter 'tst_folder' it goes in at the root instead of into wp-content:

![ac13](https://cloud.githubusercontent.com/assets/4875886/18611171/6c89a0d2-7ce6-11e6-832d-7a0f36d73298.jpg)

**Comment by morassman** [comment]
I couldn't log into WP anymore with the password you gave, so I could only test with my own FTP server. I made a small change and released v0.7.3. I tested it on my server and it worked so hopefully it works for you too.

**Comment by toonbon** [comment]
'Sorry.  I forgot you were using that install and re-purposed it.   You can use steve3, which I've set up with the same password you were using.

Yes, the .7.3 changes let me create a folder deep in a remote tree and I'm able now to rename remote folders and files.

I notice a couple of other strange things, though.  I'm not able to copy a remote folder or file from one remote to another.  Also, I'm not able to delete a remote folder if it has files in it, and I don't get any failure message explaining that you need to delete the folder contents first.  It just doesn't do anything.

Thanks,
Steve

**Comment by morassman** [comment]
Not being able to delete a folder that isn't empty is unfortunately a limitation of FTP or at least how the server implements it. The library I use does produce an error, but it simply says "Failure" without any reason why it failed. I'll add a notification and just say that one needs to make sure the folder is empty.

As for copying between remote folders. This is also a limitation of FTP. This has already been discussed [here](https://github.com/morassman/atom-commander/issues/17)

**Comment by toonbon** [comment]
Ok.  Thanks for  fixing the remote rename and the remote folder creation.  That makes the product a lot more useful for me.
